project_id = "bbepprxkkwdfzmiycqqi"

[functions.api]
verify_jwt = false

[functions.strowallet-webhook]
verify_jwt = false

[functions.yengapay-webhook]
verify_jwt = false

[functions.pay]
verify_jwt = false

[functions.reconcile-withdrawals]
verify_jwt = false

[functions.business-coach]
verify_jwt = false

[functions.whatsapp-bridge]
verify_jwt = false

[functions.bot-ai]
verify_jwt = false