/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicYengapayWebhookRouteImport } from './routes/api/public/yengapay-webhook'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicYengapayWebhookRoute =
  ApiPublicYengapayWebhookRouteImport.update({
    id: '/api/public/yengapay-webhook',
    path: '/api/public/yengapay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cards': typeof CardsRoute
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/wallet': typeof WalletRoute
  '/api/public/yengapay-webhook': typeof ApiPublicYengapayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cards': typeof CardsRoute
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/wallet': typeof WalletRoute
  '/api/public/yengapay-webhook': typeof ApiPublicYengapayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cards': typeof CardsRoute
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/wallet': typeof WalletRoute
  '/api/public/yengapay-webhook': typeof ApiPublicYengapayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cards'
    | '/dashboard'
    | '/pricing'
    | '/wallet'
    | '/api/public/yengapay-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/cards'
    | '/dashboard'
    | '/pricing'
    | '/wallet'
    | '/api/public/yengapay-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cards'
    | '/dashboard'
    | '/pricing'
    | '/wallet'
    | '/api/public/yengapay-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CardsRoute: typeof CardsRoute
  DashboardRoute: typeof DashboardRoute
  PricingRoute: typeof PricingRoute
  WalletRoute: typeof WalletRoute
  ApiPublicYengapayWebhookRoute: typeof ApiPublicYengapayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/yengapay-webhook': {
      id: '/api/public/yengapay-webhook'
      path: '/api/public/yengapay-webhook'
      fullPath: '/api/public/yengapay-webhook'
      preLoaderRoute: typeof ApiPublicYengapayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CardsRoute: CardsRoute,
  DashboardRoute: DashboardRoute,
  PricingRoute: PricingRoute,
  WalletRoute: WalletRoute,
  ApiPublicYengapayWebhookRoute: ApiPublicYengapayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
