INSERT INTO public.shop_templates (name, slug, category, description, price, is_free, created_at, updated_at) VALUES
('E-commerce Pro Dark', 'ecommerce-pro-dark', 'ecommerce', 'Design moderne et sombre optimisé pour la vente de produits high-tech.', 0, true, now(), now()),
('Boutique Mode Minimal', 'mode-minimal', 'ecommerce', 'Style minimaliste épuré idéal pour les marques de vêtements de luxe.', 0, true, now(), now()),
('Restaurant & Food Delivery', 'food-delivery', 'food', 'Interface colorée avec focus sur les photos de plats et commande rapide.', 0, true, now(), now()),
('Services Professionnels', 'services-pro', 'service', 'Idéal pour consultants, agences et prestataires de services B2B.', 0, true, now(), now()),
('Portfolio Créatif', 'portfolio-creative', 'portfolio', 'Showcase visuel pour photographes, designers et artistes.', 0, true, now(), now()),
('Luxe & Bijouterie', 'luxury-jewelry', 'luxury', 'Palette dorée et typographie élégante pour produits haut de gamme.', 0, true, now(), now()),
('Tech Gadgets Store', 'tech-gadgets', 'ecommerce', 'Layout dynamique pour les derniers produits technologiques.', 0, true, now(), now()),
('Beauty & Cosmetics', 'beauty-cosmetics', 'ecommerce', 'Couleurs douces et design soigné pour produits de beauté.', 0, true, now(), now()),
('Sport & Fitness Shop', 'sport-fitness', 'ecommerce', 'Design énergique pour équipements sportifs et compléments.', 0, true, now(), now()),
('Organic Grocery', 'organic-grocery', 'ecommerce', 'Style naturel et frais pour produits bio et alimentation.', 0, true, now(), now()),
('Home Decor & Furniture', 'home-decor', 'ecommerce', 'Ambiance chaleureuse pour le mobilier et la décoration intérieure.', 0, true, now(), now()),
('Digital Products Marketplace', 'digital-marketplace', 'ecommerce', 'Optimisé pour les téléchargements de logiciels et assets digitaux.', 0, true, now(), now()),
('Educational Courses', 'edu-courses', 'service', 'Vente de formations en ligne et contenus pédagogiques.', 0, true, now(), now()),
('Event Ticketing', 'event-tickets', 'service', 'Simple et efficace pour la vente de billets d''événements.', 0, true, now(), now()),
('Real Estate Showcase', 'real-estate', 'service', 'Présentation élégante de biens immobiliers et projets.', 0, true, now(), now()),
('Automotive Parts', 'automotive-parts', 'ecommerce', 'Robuste et clair pour pièces détachées et accessoires auto.', 0, true, now(), now()),
('Pet Supplies Boutique', 'pet-supplies', 'ecommerce', 'Design ludique pour le bonheur de nos amis les bêtes.', 0, true, now(), now()),
('Gaming Hardware Store', 'gaming-store', 'ecommerce', 'Look futuriste avec accents RGB pour les gamers.', 0, true, now(), now()),
('Art & Gallery', 'art-gallery', 'portfolio', 'Focus sur l''œuvre d''art, cadre minimal et spacieux.', 0, true, now(), now()),
('Coffee & Bakery', 'coffee-bakery', 'food', 'Ambiance café cosy pour pâtisseries et boissons.', 0, true, now(), now()),
('Medical & Health Care', 'medical-health', 'service', 'Professionnel et rassurant pour services de santé.', 0, true, now(), now()),
('Travel & Adventure', 'travel-adventure', 'service', 'Inspiration au voyage pour agences et circuits.', 0, true, now(), now()),
('Kids & Toys Shop', 'kids-toys', 'ecommerce', 'Coloré et joyeux pour les enfants et les parents.', 0, true, now(), now()),
('Watch Shop Classic', 'watch-classic', 'luxury', 'Intemporel et précis pour l''horlogerie de prestige.', 0, true, now(), now()),
('Wine & Spirits Store', 'wine-spirits', 'luxury', 'Sombre et raffiné pour les caves à vin et spiritueux.', 0, true, now(), now()),
('Handmade Crafts Shop', 'handmade-crafts', 'ecommerce', 'Style artisanal pour produits faits main et uniques.', 0, true, now(), now()),
('Photography Studio', 'photo-studio', 'portfolio', 'Showcase plein écran pour les séances photo.', 0, true, now(), now()),
('Architecture Portfolio', 'architecture-pro', 'portfolio', 'Structurel et propre pour les cabinets d''architectes.', 0, true, now(), now()),
('Legal & Finance Advice', 'legal-finance', 'service', 'Sobre et institutionnel pour cabinets d''avocats et experts.', 0, true, now(), now()),
('Music & Audio Store', 'music-store', 'ecommerce', 'Rythmé et moderne pour instruments et matériel audio.', 0, true, now(), now()),
('Gardening & Plant Shop', 'garden-plants', 'ecommerce', 'Vert et vivifiant pour les amoureux de la nature.', 0, true, now(), now()),
('Fashion Blog & Shop', 'fashion-blog', 'ecommerce', 'Mélange éditorial et vente pour influenceurs mode.', 0, true, now(), now()),
('Gym & Personal Training', 'gym-personal', 'service', 'Puissant et motivant pour les salles de sport.', 0, true, now(), now()),
('Solar & Green Energy', 'green-energy', 'service', 'Eco-responsable pour solutions énergétiques durables.', 0, true, now(), now()),
('Jewelry Design Studio', 'jewelry-design', 'luxury', 'Focus sur le détail et l''éclat des créations.', 0, true, now(), now()),
('Barber Shop & Grooming', 'barber-grooming', 'service', 'Style vintage et masculin pour les barbiers.', 0, true, now(), now()),
('Florist & Flower Delivery', 'florist-delivery', 'ecommerce', 'Délicat et parfumé pour bouquets et cadeaux.', 0, true, now(), now()),
('Gift Card Store', 'gift-cards', 'ecommerce', 'Simple et rapide pour offrir du plaisir.', 0, true, now(), now()),
('Subscription Box Service', 'subscription-box', 'ecommerce', 'Optimisé pour les modèles de vente récurrente.', 0, true, now(), now()),
('Faso-Invest Pay Signature', 'signature-template', 'luxury', 'Le template premium ultime intégrant toutes les fonctions.', 0, true, now(), now());
